#ifndef FGMVWRITE_H
#define FGMVWRITE_H

#include <FortranCInterface_names.h>

#define gmvwrite_openfile_ir_f TR_ROUTINE_GLOBAL_(gmvwrite_openfile_ir_f,GMVWRITE_OPENFILE_IR_F)
#define gmvwrite_openfile_ir_ascii_f TR_ROUTINE_GLOBAL_(gmvwrite_openfile_ir_ascii_f,GMVWRITE_OPENFILE_IR_ASCII_F)
#define gmvwrite_closefile_f TR_ROUTINE_GLOBAL_(gmvwrite_closefile_f,GMVWRITE_CLOSEFILE_F)
#define gmvwrite_probtime_f TR_ROUTINE_GLOBAL_(gmvwrite_probtime_f,GMVWRITE_PROBTIME_F)
#define gmvwrite_cycleno_f TR_ROUTINE_GLOBAL_(gmvwrite_cycleno_f,GMVWRITE_CYCLENO_F)
#define gmvwrite_node_data_f TR_ROUTINE_GLOBAL_(gmvwrite_node_data_f,GMVWRITE_NODE_DATA_F)
#define gmvwrite_nodeids_f TR_ROUTINE_GLOBAL_(gmvwrite_nodeids_f,GMVWRITE_NODEIDS_F)
#define gmvwrite_cell_type_f TR_ROUTINE_GLOBAL_(gmvwrite_cell_type_f,GMVWRITE_CELL_TYPE_F)
#define gmvwrite_cell_header_f TR_ROUTINE_GLOBAL_(gmvwrite_cell_header_f,GMVWRITE_CELL_HEADER_F)
#define gmvwrite_cellids_f TR_ROUTINE_GLOBAL_(gmvwrite_cellids_f,GMVWRITE_CELLIDS_F)
#define gmvwrite_material_header_f TR_ROUTINE_GLOBAL_(gmvwrite_material_header_f,GMVWRITE_MATERIAL_HEADER_F)
#define gmvwrite_material_name_f TR_ROUTINE_GLOBAL_(gmvwrite_material_name_f,GMVWRITE_MATERIAL_NAME_F)
#define gmvwrite_material_ids_f TR_ROUTINE_GLOBAL_(gmvwrite_material_ids_f,GMVWRITE_MATERIAL_IDS_F)
#define gmvwrite_material_ids_f TR_ROUTINE_GLOBAL_(gmvwrite_material_ids_f,GMVWRITE_MATERIAL_IDS_F)
#define gmvwrite_variable_header_f TR_ROUTINE_GLOBAL_(gmvwrite_variable_header_f,GMVWRITE_VARIABLE_HEADER_F)
#define gmvwrite_variable_name_data_f TR_ROUTINE_GLOBAL_(gmvwrite_variable_name_data_f,GMVWRITE_VARIABLE_NAME_DATA_F)
#define gmvwrite_variable_endvars_f TR_ROUTINE_GLOBAL_(gmvwrite_variable_endvars_f,GMVWRITE_VARIABLE_ENDVARS_F)

#define gmvwrite_flag_header_f TR_ROUTINE_GLOBAL_(gmvwrite_flag_header_f,GMVWRITE_FLAG_HEADER_F)
#define gmvwrite_flag_name_f TR_ROUTINE_GLOBAL_(gmvwrite_flag_name_f,GMVWRITE_FLAG_NAME_F)
#define gmvwrite_flag_subname_f TR_ROUTINE_GLOBAL_(gmvwrite_flag_subname_f,GMVWRITE_FLAG_SUBNAME_F)
#define gmvwrite_flag_data_f TR_ROUTINE_GLOBAL_(gmvwrite_flag_data_f,GMVWRITE_FLAG_DATA_F)
#define gmvwrite_flag_endflag_f TR_ROUTINE_GLOBAL_(gmvwrite_flag_endflag_f,GMVWRITE_FLAG_ENDFLAG_F)

#endif
