target_sources(truchas PRIVATE
  diffusion_solver_namelist.F90
  thermal_bc_namelist.F90
  thermal_bc_factory_type.F90
  species_bc_namelist.F90
  species_bc_factory_type.F90
  fht_model_type.F90
  fht_vector_type.F90
  fht_norm_type.F90
  fht_precon_type.F90
  fht_ic_solver_type.F90
  fht_solver_type.F90
  cell_prop_func_class.F90
  prop_cell_func_type.F90
  thermal_component_type.F90
  thermal_component_factory.F90
  thermal_view_factor_coupling_type.F90
  species_component_type.F90
  species_component_factory.F90
  sd_vector_type.F90
  sd_model_type.F90
  sd_norm_type.F90
  sd_precon_type.F90
  sd_idaesol_model_type.F90
  sd_ic_solver_type.F90
  htsd_vector_type.F90
  htsd_idaesol_model_type.F90
  htsd_model_type.F90
  htsd_norm_type.F90
  htsd_precon_type.F90
  htsd_solver_type.F90
  htsd_ic_solver_type.F90
  sd_solver_type.F90
  ht_vector_type.F90
  ht_model_type.F90
  ht_norm_type.F90
  ht_precon_type.F90
  ht_idaesol_model_type.F90
  ht_solver_type.F90
  ht_ic_solver_type.F90
  TofH_type.F90
  mfd_disc_type.F90
  mfd_diff_matrix_type.F90
  mfd_diff_precon_type.F90
  thermal_species_solver_class.F90
  thermal_species_physics_type.F90
  thermal_species_driver.F90
  mesh_interop.F90
  enthalpy_advector_class.F90
  enthalpy_advector1_type.F90
  conc_advector_type.F90
  evap_heat_flux_type.F90
  evaporation_namelist.F90
  thermal_source_namelist.F90
  thermal_source_factory_type.F90
  species_source_namelist.F90
  species_source_factory_type.F90
)

add_subdirectory(Test)
