.TH ADDGAPS "1" "November 2005" "Telluride Project"
.SH NAME
addgaps \- add gap elements to an Exodus/Genesis-format mesh
.SH SYNOPSIS
\fBaddgaps\fP [-s] \fIinmesh outmesh ssid\fP [\fIssid\fP ...]

.SH DESCRIPTION
The \fBaddgaps\fP command reads the mesh from the Exodus/Genesis-format file
\fIinmesh\fP, inserts gap elements along user-specified mesh surfaces,
and writes the modified mesh to the Exodus/Genesis-format file \fIoutmesh\fP.
The mesh surfaces are specified by providing the ID \fIssid\fP of one
or more side sets defined in \fIinmesh\fP.  Gap elements are simply
0-thickness hex or wedge elements.  A hex gap element is inserted 
between elements neighboring a quadrilateral gap side, and a wedge
gap element is inserted between elements neighboring a triangular gap
side.  The input mesh may consist of any combination of hex, tet, or
wedge elements.

The added gap elements are assigned to new element blocks, normally
one block per specified side set; when a side set results in multiple
types of gap elements, one block per type will be used.  The user is
prompted to provide the ID assigned to each of the new element blocks.
Pre-existing element blocks are not altered.

All side sets from \fIinmesh\fP are propagated to \fIoutmesh\fP
unaltered, exept possibly for those side sets used to specify the
gap surfaces.  Unless the option \fI-s\fP is specified, the program
ensures that those latter side sets describe both sides of the gap
by adding additional sides to the side sets if necessary.

All node sets from \fIinmesh\fP are propagated to \fIoutmesh\fP.  If
a node on a gap surface belongs to a node set, it is replaced in the
node set by its daughter nodes.

.SH LIMITATIONS

Gap surfaces may not lie on the mesh boundary, in whole or part;
there must be an element on both sides of every gap side.  The program
will write an error message if such a situation is encountered.

A mesh side cannot be specified as a gap side by two different side
sets; this is a consequence of the manner gap elements are added to
element blocks.  The program writes an error message objecting to
"overlapping side sets" if such a situation is encountered.  Note that
it is perfectly fine to have a mesh side belong to multiple side sets as
long as at most one of those side sets is used to specify a gap surface.

.SH WARNINGS

The algorithm \fIaddgaps\fP uses to insert gap elements is quite general,
and the program can generate a mesh with a complex gap element topology
that \fBTruchas\fP cannot properly handle.  In order to prevent  The program will write warning
messages in the following circumstances:

1. when a node on a gap surface has been replace by more than 3 daughter
nodes.  The only type of (crossing) gap surface intersections allowed
by \fBTruchas\fP are "T"-intersections.  Other intersections will result
in more than 3 daughter nodes.  Note that the side set IDs are irrelevant
when determining the topology of gap surface
  
2. when a gap element is topologically degenerate.  This is indicative of
a gap surface that ends inside of the domain; a crack tip, for example.
\fBTruchas\fP may not be able to handle such a structure sensibly.

.SH REFERENCES

Larry A. Schoof and Victor R. Yarberry. EXODUS II: A finite element data model.
Technical Report SAND92-2137, Sandia National Laboratories, 1992.
http://endo.sandia.gov/SEACAS/Documentation/exodusII.pdf
.SH AUTHOR

Neil Carlson, CCS-2, Los Alamos National Laboratory
