#!/bin/bash

#### Runs tests for Truchas


## Stop if errors encountered
set -e


#### Parse Arguments ####
if [ ${#} -lt 2 ]; then
   echo "ERROR: This script tests Truchas made with build or build_truchas script. It requires 2 arguments"
   echo "Argument 1: Location where Truchas is installed"
   echo "Argument 2: Number of processes to use for testing"

   exit 1
elif [ ${#} -gt 2 ]; then
   echo "Ignored arguments:" ${@:3}
fi

## Go to Truchas CMake build directory. See build_truchas for BUILD_DIR
cd ${1}/build_truchas


## Build Truchas
ctest -j${2}
