# Remove the ; for a nice print out
foreach(i ${Truchas_PREPROCESSOR})
  set(Truchas_PREPROCESSOR_STRING "${Truchas_PREPROCESSOR_STRING} ${i}")
endforeach()

message("")
message("Configuration Summary")
message("=====================")
message("")
message("CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}")
if(CMAKE_BUILD_TYPE)
  message("CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}")
else()
  message("CMAKE_BUILD_TYPE not specified (this is okay)")
endif()
message("")
message("${CMAKE_C_COMPILER_ID} C compiler (version ${CMAKE_C_COMPILER_VERSION}):")
message("  CMAKE_C_COMPILER=${CMAKE_C_COMPILER}")
message("  CMAKE_C_FLAGS=${CMAKE_C_FLAGS}")
if(CMAKE_BUILD_TYPE)
  message("  CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UC}=${CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UC}}")
endif()
message("")

message("${CMAKE_Fortran_COMPILER_ID} Fortran compiler (version ${CMAKE_Fortran_COMPILER_VERSION}):")
message("  CMAKE_Fortran_COMPILER=${CMAKE_Fortran_COMPILER}")
message("  CMAKE_Fortran_FLAGS=${CMAKE_Fortran_FLAGS}")
if(CMAKE_BUILD_TYPE)
  message("  CMAKE_Fortran_FLAGS_${CMAKE_BUILD_TYPE_UC}=${CMAKE_Fortran_FLAGS_${CMAKE_BUILD_TYPE_UC}}")
endif()
message("  Fortran source preprocessor command: ${Truchas_PREPROCESSOR_STRING}")
message("")

message("MPI:")
message("  MPI_C_COMPILER=${MPI_C_COMPILER}")
message("  MPI_C_INCLUDE_PATH=${MPI_C_INCLUDE_PATH}")
message("  MPI_C_LIBRARIES=${MPI_C_LIBRARIES}")
message("  MPIEXEC=${MPIEXEC}")
message("  MPIEXEC_NUMPROC_FLAG=${MPIEXEC_NUMPROC_FLAG}")
message("")

message("Python (version ${PYTHON_VERSION_STRING}): ${PYTHON_EXECUTABLE}")
message("")

message("LAPACK library:")
message("  LAPACK_LINKER_FLAGS=${LAPACK_LINKER_FLAGS}")
message("  LAPACK_LIBRARIES=${LAPACK_LIBRARIES}")
message("")

message("Parallel HYPRE library (version ${HYPRE_VERSION}):")
message("  HYPRE target=HYPRE::HYPRE")
message("  HYPRE_WITH_MPI=${HYPRE_WITH_MPI}")
message("  HYPRE_ENABLE_SHARED=${HYPRE_ENABLE_SHARED}")
message("")

message("HDF5 library (version ${HDF5_VERSION_STRING}):")
message("  HDF5 target=hdf5::hdf5")
message("  HDF5_ENABLE_PARALLEL=${HDF5_ENABLE_PARALLEL}")
message("  HDF5_BUILD_HL_LIB=${HDF5_BUILD_HL_LIB}")
message("")

message("fVTKHDF library:")
message("  fVTKHDF target=fVTKHDF::fvtkhdf")
message("  fVTKHDF_MPI_SUPPORT=${fVTKHDF_MPI_SUPPORT}")
message("  fVTKHDF_MPI_F08_SUPPORT=${fVTKHDF_MPI_F08_SUPPORT}")
message("")

if(USE_MUMPS)
  message("MUMPS library (version ${MUMPS_VERSION}):")
  message("  MUMPS targets=MUMPS::DMUMPS;MUMPS::ZMUMPS")
  message("  MUMPS_parallel=${MUMPS_parallel}")
  message("  MUMPS_intsize64=${MUMPS_intsize64}")
  message("")
endif()

message("NetCDF library (version ${NetCDFVersion}):")
message("  netCDF target=netCDF::netcdf")
message("  netCDF_INCLUDE_DIR=${netCDF_INCLUDE_DIR}")
message("  netCDF_HAS_NC4=${netCDF_HAS_NC4}")
message("  netCDF_HAS_PARALLEL=${netCDF_HAS_PARALLEL}")
message("")

message("ExodusII library:")
message("  Exodus target=SEACASExodus::exodus")
message("  SEACASExodus_INSTALL_DIR=${SEACASExodus_INSTALL_DIR}")
message("  SEACASExodus_ENABLE_Netcdf=${SEACASExodus_ENABLE_Netcdf}")
message("  SEACASExodus_ENABLE_MPI=${SEACASExodus_ENABLE_MPI}")
message("")

message("Petaca library (version ${PETACA_VERSION}):")
message("  PETACA_LIBRARIES=${PETACA_LIBRARIES}")
message("  PETACA_INCLUDE_DIRS=${PETACA_INCLUDE_DIRS}")
message("")

message("Chaparral library (version ${Chaparral_VERSION}):")
message("  Chaparral target=Chaparral::Chaparral")
message("  Chaparral_LIBRARY_DIR=${Chaparral_LIBRARY_DIR}")
message("  Chaparral_INCLUDE_DIRS=${Chaparral_INCLUDE_DIRS}")
message("")

message("Scorpio library (version ${SCORPIO_VERSION}):")
message("  SCORPIO_LIBRARY=${SCORPIO_LIBRARY}")
message("")

message("Metis library (version ${METIS_VERSION}):")
message("  METIS target=METIS::METIS")
message("  METIS_LIBRARY=${METIS_LIBRARY}")
message("  METIS_INCLUDE_DIR=${METIS_INCLUDE_DIR}")
message("")

if(USE_PORTAGE)
  message("Portage installation:")
  message("  WONTON_ROOT=${WONTON_ROOT}")
  message("  PORTAGE_ROOT=${PORTAGE_ROOT}")
  message("")
endif()
