#===============================================================================
#
# This file is part of Truchas. 3-Clause BSD license; see the LICENSE file.
#
#===============================================================================

import os

import h5py
import numpy as np

from . import truchas_geometry as tg


class TruchasEMData:
    """A class for reading Truchas EM output data.

    This class currently makes the following assumptions:

    1. The EM mesh is tetrahedral.
    2. The requested EM block exists in the VTKHDF assembly.
    3. The mesh and fields are written in the current parallel VTKHDF layout.
    4. Fields returned by :meth:`field` are cell-centered.

    :param filename: Filename of the Truchas FDME VTKHDF output file.
    :type filename: str
    :param blockname: Name of the EM block to read from the VTKHDF assembly.
    :type blockname: str
    """

    def __init__(self, filename, blockname):
        self.filename = filename
        """The filename of the VTKHDF Truchas output."""
        self.blockname = blockname
        """The name of the mesh block in the VTKHDF file."""
        self.directory = os.path.dirname(filename)
        self._root = h5py.File(filename, 'r')
        self._centroid = None
        self._volume = None
        self._node_coordinates = None
        self._cnode = None

        assembly = self._root["VTKHDF/Assembly"]
        if self.blockname not in assembly:
            raise ValueError(
                f"Block {self.blockname!r} not found in {filename}."
            )

        self._block_path = f"VTKHDF/Assembly/{self.blockname}"
        self._num_cells_per_rank = self._root[f"{self._block_path}/NumberOfCells"][:]
        self._num_points_per_rank = self._root[f"{self._block_path}/NumberOfPoints"][:]
        self._num_conn_ids_per_rank = self._root[f"{self._block_path}/NumberOfConnectivityIds"][:]

        self.ncell = int(np.sum(self._num_cells_per_rank))
        self.nnode = int(np.sum(self._num_points_per_rank))

        self._compute_maps()


    def field(self, field_name):
        """Return the requested field as a ndarray. This will read the entire
        field from disk.

        :param field_name: The name of a field in the Truchas output file. Valid
            values include ``"E_im"``, ``"E_re"``, ``"H_im"``, ``"H_re"``,
            ``"|E|"``, ``"|H|"``, ``"Q_EM"``, ``"MPI rank"``.
        :type field_name: str

        :return: The requested field from the H5 file.
        :rtype: :class:`numpy.ndarray`

        """
        return self._root[f"{self._block_path}/CellData/{field_name}"][:][self._cellmap]


    def _cell_node_map(self):
        """Load the cell-to-node map for the full EM mesh.

        In the parallel VTKHDF layout, point and cell data are concatenated by
        MPI rank. Connectivity ids are therefore rank-local, and the offsets
        restart from zero at each rank boundary. Rebuild a single global map by
        stitching those rank-local sections together and shifting node ids by
        the cumulative number of points from earlier ranks.
        """
        if self._cnode is None:
            connectivity = self._root[f"{self._block_path}/Connectivity"][:]
            offsets = self._root[f"{self._block_path}/Offsets"][:]
            point_bases = np.cumsum(np.concatenate(([0], self._num_points_per_rank[:-1])))

            cnode = []
            conn_pos = 0
            offset_pos = 0
            for ncell, nconn, point_base in zip(self._num_cells_per_rank,
                                                self._num_conn_ids_per_rank,
                                                point_bases):
                local_offsets = offsets[offset_pos:offset_pos + ncell + 1]
                local_connectivity = connectivity[conn_pos:conn_pos + nconn]
                cnode.extend(
                    local_connectivity[local_offsets[i]:local_offsets[i + 1]] + point_base
                    for i in range(ncell)
                )
                conn_pos += nconn
                offset_pos += ncell + 1

            self._cnode = np.array(cnode)
        return self._cnode


    def _compute_maps(self):
        """Compute a processor-independent mapping of the data. NB: This mapping
        is orientation-dependent, since it is generated by sorting the cell
        centroids.

        Parallel VTKHDF output duplicates shared points on partition boundaries.
        Collapse identical coordinates to a single logical node before building
        the cell ordering, so the resulting canonical mesh matches equivalent
        serial output.
        """
        xn = self.node_coordinates()
        sorted_nodes = np.argsort(xn.view(dtype="f8,f8,f8"), axis=0, order=["f0","f1","f2"])[:,0]
        sorted_coords = xn[sorted_nodes]

        # The first occurrence of each coordinate tuple becomes the canonical
        # node representative; later duplicates map back to that same node.
        unique_mask = np.concatenate(([True],
                                      np.any(sorted_coords[1:] != sorted_coords[:-1], axis=1)))
        self._nodemap = sorted_nodes[unique_mask]
        self._node_coordinates = sorted_coords[unique_mask]
        self.nnode = len(self._node_coordinates)

        inodemap = np.empty(len(sorted_nodes), dtype=np.int64)
        inodemap[sorted_nodes] = np.cumsum(unique_mask) - 1
        self._cell_node_map()
        self._cnode = np.sort(inodemap[self._cnode])
        self._cellmap = np.argsort(self._cnode.view("i8,i8,i8,i8"), axis=0,
                                   order=["f0","f1","f2","f3"])[:,0]
        self._cnode = self._cnode[self._cellmap]


    def centroids(self):
        """
        :return: A ``[ncell,3]`` field of cell centroids.
        :rtype: :class:`numpy.ndarray`
        """
        if self._centroid is None:
            x = self.node_coordinates()
            cnode = self._cell_node_map()
            self._centroid = np.array([x[cn,:].mean(axis=0) for cn in cnode])
        return self._centroid


    def volumes(self):
        """
        :return: A length ``ncell`` field of cell volumes.
        :rtype: :class:`numpy.ndarray`
        """
        if self._volume is None:
            x = self.node_coordinates()
            cnode = self._cell_node_map()
            self._volume = np.array([tg.tet_volume(x[cn,:]) for cn in cnode])
            self._volume = self._volume[self._cellmap]
        return self._volume


    def node_coordinates(self):
        """
        Return the canonical node coordinates with duplicated partition-boundary
        points removed.

        :return: A ``[nnode,3]`` field of node coordinates.
        :rtype: :class:`numpy.ndarray`
        """
        if self._node_coordinates is None:
            self._node_coordinates = self._root[f"{self._block_path}/Points"][:]
        return self._node_coordinates
